<?php

/**
 * @file
 * Contains landing page functionality for Lightning.
 */

use Drupal\node\Entity\NodeType;
use Drupal\workflows\Entity\Workflow;

/**
 * Implements hook_modules_installed().
 */
function lightning_landing_page_modules_installed(array $modules) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  $node_type = NodeType::load('landing_page');

  // If Layout Library is installed, the layout_selection field will be
  // available on the landing page content type, so it should be displayed on
  // the node form.
  if (in_array('layout_library', $modules, TRUE)) {
    // Show a select list if Options is installed. Otherwise, fall back to an
    // auto-completing text field.
    $widget_type = Drupal::moduleHandler()->moduleExists('options')
      ? 'options_select'
      : 'entity_reference_autocomplete';

    lightning_layout_entity_get_form_display('node', $node_type->id(), 'default')
      ->setComponent('layout_selection', [
        'type' => $widget_type,
        'region' => 'content',
      ])
      ->save();
  }

  if (in_array('lightning_search', $modules, TRUE)) {
    lightning_search_node_type_insert($node_type);
  }

  if (in_array('lightning_workflow', $modules, TRUE)) {
    $workflow = Workflow::load('editorial');
    /** @var \Drupal\content_moderation\Plugin\WorkflowType\ContentModerationInterface $plugin */
    $plugin = $workflow->getTypePlugin();
    $plugin->addEntityTypeAndBundle('node', $node_type->id());
    $workflow->save();
  }

  if (in_array('menu_ui', $modules, TRUE)) {
    $node_type
      ->setThirdPartySetting('menu_ui', 'available_menus', ['main'])
      ->setThirdPartySetting('menu_ui', 'parent', 'main:')
      ->save();
  }
}
