<?php
/**
 * Implements hook_theme().
 */
function stockinfo_theme($existing, $type, $theme, $path) {
  return [
    'stockinfo_block' => [
      'variables' => [
        'symbol' => NULL,
        'price' => NULL,
        'change' => NULL,
        'volume' => NULL,
      ],
      'template' => 'stockinfoblock',
    ],
    'stockinfo_block_square' => [
      'variables' => [
        'symbol' => NULL,
        'price' => NULL,
        'change' => NULL,
        'volume' => NULL,
      ],
      'template' => 'stockinfoblocksquare',
    ],
  ];
}
