<?php

/**
 * @file
 * Contains installation and update routines for Lightning Page.
 */

/**
 * Implements hook_install().
 */
function lightning_page_install() {
  $modules = [
    'layout_library',
    'lightning_workflow',
    'menu_ui',
  ];

  $modules = array_filter($modules, [Drupal::moduleHandler(), 'moduleExists']);
  if ($modules) {
    lightning_page_modules_installed($modules);
  }
}
